width = 10
height = 10
color_names = ["Whyte"]
color_values = [
 [ 255, 255, 255 ]
]


x = [
  [ [1,7], [0,1], [1,2] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [1,9], [0,1] ],
  [ [0,7], [1,1], [0,2] ],
  [ [0,9], [1,1] ]
]
y = [
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [1,8], [0,2] ],
  [ [0,1], [1,8], [0,1] ],
  [ [0,1], [0,1], [0,7], [1,1] ]
]